# Create the following directory variables.
oLib = ../../../../"CenyML library skeleton"/otherLibraries
cM = ../../../../"CenyML library skeleton"/CenyML_Library

main.x:
	gcc main.c $(oLib)/time/mTimeTer.c $(oLib)/csv/csvManager.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c -O3 -o main.x
