# Create the following directory variables.
oLib = ../../../../"CenyML library skeleton"/otherLibraries
cM = ../../../../"CenyML library skeleton"/CenyML_Library
time = mTime.c # header file to measure time in Linux Ubuntu
#time = mTimeTer.c # header file to measure time in Cygwin terminal window

main_raisetoTheFirstPowerRegression.x:
	gcc main_raisetoTheFirstPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raisetoTheFirstPowerRegression.x -lm

main_simpleLinearRegressionWithRelu.x:
	gcc main_simpleLinearRegressionWithRelu.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_simpleLinearRegressionWithRelu.x -lm

main_hyperbolicTangentRegression.x:
	gcc main_hyperbolicTangentRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_hyperbolicTangentRegression.x -lm

main_logisticRegression.x:
	gcc main_logisticRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_logisticRegression.x -lm

main_raiseToTheSecondPowerRegression.x:
	gcc main_raiseToTheSecondPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raiseToTheSecondPowerRegression.x -lm

main_raiseToTheThirdPowerRegression.x:
	gcc main_raiseToTheThirdPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raiseToTheThirdPowerRegression.x -lm

main_raiseToTheFourthPowerRegression.x:
	gcc main_raiseToTheFourthPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raiseToTheFourthPowerRegression.x -lm

main_raiseToTheFifthPowerRegression.x:
	gcc main_raiseToTheFifthPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raiseToTheFifthPowerRegression.x -lm

main_raiseToTheSixthPowerRegression.x:
	gcc main_raiseToTheSixthPowerRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_raiseToTheSixthPowerRegression.x -lm

main_firstOrderExponentialRegression.x:
	gcc main_firstOrderExponentialRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_firstOrderExponentialRegression.x -lm

main_secondOrderExponentialRegression.x:
	gcc main_secondOrderExponentialRegression.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLregressionEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_secondOrderExponentialRegression.x -lm

main_linearClassification.x:
	gcc main_linearClassification.c $(oLib)/time/$(time) $(oLib)/csv/csvManager.c $(oLib)/pbPlots/pbPlots.c $(oLib)/pbPlots/supportLib.c $(cM)/cpuSequential/evaluationMetrics/CenyMLclassificationEvalMet.c $(cM)/cpuSequential/machineLearning/CenyMLdeepLearning.c -O3 -o main_linearClassification.x -lm
