# Create the following directory variables.
oLib = ../../../../"CenyML Library"/otherLibraries
cM = ../../../../"CenyML Library"/CenyML_Library

main.x:
	gcc main.c $(oLib)/time/mTimeTer.c $(oLib)/csv/csvManager.c $(cM)/cpuSequential/statistics/CenyMLstatistics.c -O3 -o main.x
